#logging:
#  level:
#    org.springframework.security: INFO

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.27.32:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#endpoints:
#  health:
#    sensitive: false
#    enabled: true
#  actuator:
#    enabled: true
#    sensitive: false
#  beans:
#    sensitive: false
#    enabled: true


management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true


