hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    user-service:
      path: /userapi/**
      serviceId: user-service
      sensitiveHeaders:

    preprocess-service:
      path: /preprocessapi/**
      serviceId: preprocess-service
      sensitiveHeaders:

    wechat-service:
      path: /wechatapi/**
      serviceId: wechat-service
      sensitiveHeaders:

server:
  port: 80

spring:
  zipkin:
    base-url: http://120.79.27.32:9411
