spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ytkj_log?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: rys87tgD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9997