server:
  port: 8768


spring:
  zipkin:
    base-url: http://172.17.0.1:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    ytkjpreprocess:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ytkj_preprocess?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: rys87tgD
    ytkjsentence:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ytkj_sentence?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: rys87tgD
