server:
  port: 8762


spring:
  zipkin:
    base-url: http://120.79.27.32:9411

#  rabbitmq:
#    host: localhost
#    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.27.32:3306/ytkj_user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: rys87tgD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.27.32:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "1.1.1.1"