server:
  port: 8767


spring:
  zipkin:
    base-url: http://120.79.27.32:9411

  rabbitmq:
    host: 120.79.27.32
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /